name: 🔖 Bump Build Version
description: "Bump Build Version"

inputs:
  token:
    description: The VENLY_GITHUB_ACTIONS_TOKEN
    required: true
  commit_message:
    description: The commit message to use
    required: false
    default: "chore() - Bump version [skip ci]"

outputs:
  new_version:
    description: "Bumped Version"
    value: ${{ steps.bump_version.outputs.new_version }}

runs:
  using: "composite"
  steps:
    - uses: oleksiyrudenko/gha-git-credentials@v2.1.1
      with:
        global: false
        name: ${{ github.actor }}
        email: ${{ github.actor }}@venly.io
        actor: ${{ github.actor }}
        token: ${{ inputs.token }}

    - name: 🔖 Bump Version
      id: bump_version
      shell: bash
      run: |
        #!/bin/bash
        set -x
        new_version=$(npm version prerelease --preid=develop --git-tag-version=false)
        new_version=${new_version#v}
        echo "Version after bump: $(jq -r '.version' package.json)"
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "new_version=$new_version" >> $GITHUB_OUTPUT

    - name: Commit version bump
      id: commit_version_bump
      shell: bash
      run: |
        #!/bin/bash
        set -x
        git commit -a -m ${{ inputs.commit_message }}

    - name: Push version bump
      id: push_version_bump
      shell: bash
      run: |
        #!/bin/bash
        set -x
        git push origin